# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcs < Formula
  desc "CLI for Dilmune Cloud Services"
  homepage "https://dilmune.com"
  version "3.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dilmune/dcs-cli/releases/download/v3.6.0/dcs_darwin_amd64.tar.gz"
      sha256 "b7eba7f592cca9eb02052e62726a2adb8b5e83348478889326874f41ec78b4a3"

      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dilmune/dcs-cli/releases/download/v3.6.0/dcs_darwin_arm64.tar.gz"
      sha256 "e5fbdd1bfe3270c0565c9bae6df4c1a443904334f05dc5881fdfe5d1cd2c1f15"

      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs-cli/releases/download/v3.6.0/dcs_linux_amd64.tar.gz"
      sha256 "ac5d75591abed84e0218c0ff01604e58c79087b5cdedf6eaf00cff2ce81e5d3c"
      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs-cli/releases/download/v3.6.0/dcs_linux_arm64.tar.gz"
      sha256 "d42ea27f00d8834e94d5b98163f605c3eb986d6f718b8499bc5fe65ecfb3bd15"
      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  test do
    system "#{bin}/dcs", "version", "--json"
  end
end
