# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcs < Formula
  desc "CLI for Dilmune Cloud Services"
  homepage "https://dilmune.com"
  version "3.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_darwin_amd64.tar.gz"
      sha256 "74a03d9ef6d0314761c44c94783e4d75a2d391147ceeb41fb737c29bdf66b518"

      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_darwin_arm64.tar.gz"
      sha256 "537b4729a683e5d2c8e23dad3ae67973eb088a97e22d539fd24913a5f1a8f158"

      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_linux_amd64.tar.gz"
      sha256 "a49609a673d855e806676614891d15af29d528f478cbae3f180a8239580f1fd2"
      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_linux_arm64.tar.gz"
      sha256 "ed6de6eae064954d370de51f35084fa91faf6ccb9800945a9f31e6fa48dc10ab"
      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  test do
    system "#{bin}/dcs", "version", "--json"
  end
end
