# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcs < Formula
  desc "CLI for Dilmune Cloud Services"
  homepage "https://dilmune.com"
  version "3.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_darwin_amd64.tar.gz"
      sha256 "6e99503956672772b371502e6584ce8c3e2938d9ea68a667c5843d0b5ac0689d"

      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_darwin_arm64.tar.gz"
      sha256 "fac73e9aabe615b9e5d1f7cb400010857ff15ec07d1cde43af368d0d33e8d7b7"

      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_linux_amd64.tar.gz"
      sha256 "e4ccfc15c26272820dd916251b0c04bb76d55a9f0336a26dac65f3372f77d6a7"
      define_method(:install) do
        bin.install "dcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dilmune/dcs/releases/download/v3.6.0/dcs_linux_arm64.tar.gz"
      sha256 "6123576484c0d8f79ae380c0a42b2fe45256c009aa285fd0c0235fc57a3fc082"
      define_method(:install) do
        bin.install "dcs"
      end
    end
  end

  test do
    system "#{bin}/dcs", "version", "--json"
  end
end
